//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clientes.Web.ClientesWcReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteModel", Namespace="http://schemas.datacontract.org/2004/07/Clientes.WcService")]
    [System.SerializableAttribute()]
    public partial class ClienteModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CpfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSituacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeSituacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Cpf {
            get {
                return this.CpfField;
            }
            set {
                if ((object.ReferenceEquals(this.CpfField, value) != true)) {
                    this.CpfField = value;
                    this.RaisePropertyChanged("Cpf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int IdSituacao {
            get {
                return this.IdSituacaoField;
            }
            set {
                if ((this.IdSituacaoField.Equals(value) != true)) {
                    this.IdSituacaoField = value;
                    this.RaisePropertyChanged("IdSituacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string NomeSituacao {
            get {
                return this.NomeSituacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeSituacaoField, value) != true)) {
                    this.NomeSituacaoField = value;
                    this.RaisePropertyChanged("NomeSituacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SituacaoClienteModel", Namespace="http://schemas.datacontract.org/2004/07/Clientes.WcService")]
    [System.SerializableAttribute()]
    public partial class SituacaoClienteModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientesWcReference.IClienteService")]
    public interface IClienteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ListarClientes", ReplyAction="http://tempuri.org/IClienteService/ListarClientesResponse")]
        Clientes.Web.ClientesWcReference.ClienteModel[] ListarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ListarClientes", ReplyAction="http://tempuri.org/IClienteService/ListarClientesResponse")]
        System.Threading.Tasks.Task<Clientes.Web.ClientesWcReference.ClienteModel[]> ListarClientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ObterCliente", ReplyAction="http://tempuri.org/IClienteService/ObterClienteResponse")]
        Clientes.Web.ClientesWcReference.ClienteModel ObterCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ObterCliente", ReplyAction="http://tempuri.org/IClienteService/ObterClienteResponse")]
        System.Threading.Tasks.Task<Clientes.Web.ClientesWcReference.ClienteModel> ObterClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/CriarCliente", ReplyAction="http://tempuri.org/IClienteService/CriarClienteResponse")]
        bool CriarCliente(Clientes.Web.ClientesWcReference.ClienteModel cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/CriarCliente", ReplyAction="http://tempuri.org/IClienteService/CriarClienteResponse")]
        System.Threading.Tasks.Task<bool> CriarClienteAsync(Clientes.Web.ClientesWcReference.ClienteModel cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/AtualizarCliente", ReplyAction="http://tempuri.org/IClienteService/AtualizarClienteResponse")]
        bool AtualizarCliente(Clientes.Web.ClientesWcReference.ClienteModel cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/AtualizarCliente", ReplyAction="http://tempuri.org/IClienteService/AtualizarClienteResponse")]
        System.Threading.Tasks.Task<bool> AtualizarClienteAsync(Clientes.Web.ClientesWcReference.ClienteModel cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ExcluirCliente", ReplyAction="http://tempuri.org/IClienteService/ExcluirClienteResponse")]
        bool ExcluirCliente(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ExcluirCliente", ReplyAction="http://tempuri.org/IClienteService/ExcluirClienteResponse")]
        System.Threading.Tasks.Task<bool> ExcluirClienteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ListarSituacoes", ReplyAction="http://tempuri.org/IClienteService/ListarSituacoesResponse")]
        Clientes.Web.ClientesWcReference.SituacaoClienteModel[] ListarSituacoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClienteService/ListarSituacoes", ReplyAction="http://tempuri.org/IClienteService/ListarSituacoesResponse")]
        System.Threading.Tasks.Task<Clientes.Web.ClientesWcReference.SituacaoClienteModel[]> ListarSituacoesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IClienteServiceChannel : Clientes.Web.ClientesWcReference.IClienteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClienteServiceClient : System.ServiceModel.ClientBase<Clientes.Web.ClientesWcReference.IClienteService>, Clientes.Web.ClientesWcReference.IClienteService {
        
        public ClienteServiceClient() {
        }
        
        public ClienteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClienteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Clientes.Web.ClientesWcReference.ClienteModel[] ListarClientes() {
            return base.Channel.ListarClientes();
        }
        
        public System.Threading.Tasks.Task<Clientes.Web.ClientesWcReference.ClienteModel[]> ListarClientesAsync() {
            return base.Channel.ListarClientesAsync();
        }
        
        public Clientes.Web.ClientesWcReference.ClienteModel ObterCliente(int id) {
            return base.Channel.ObterCliente(id);
        }
        
        public System.Threading.Tasks.Task<Clientes.Web.ClientesWcReference.ClienteModel> ObterClienteAsync(int id) {
            return base.Channel.ObterClienteAsync(id);
        }
        
        public bool CriarCliente(Clientes.Web.ClientesWcReference.ClienteModel cliente) {
            return base.Channel.CriarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> CriarClienteAsync(Clientes.Web.ClientesWcReference.ClienteModel cliente) {
            return base.Channel.CriarClienteAsync(cliente);
        }
        
        public bool AtualizarCliente(Clientes.Web.ClientesWcReference.ClienteModel cliente) {
            return base.Channel.AtualizarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<bool> AtualizarClienteAsync(Clientes.Web.ClientesWcReference.ClienteModel cliente) {
            return base.Channel.AtualizarClienteAsync(cliente);
        }
        
        public bool ExcluirCliente(int id) {
            return base.Channel.ExcluirCliente(id);
        }
        
        public System.Threading.Tasks.Task<bool> ExcluirClienteAsync(int id) {
            return base.Channel.ExcluirClienteAsync(id);
        }
        
        public Clientes.Web.ClientesWcReference.SituacaoClienteModel[] ListarSituacoes() {
            return base.Channel.ListarSituacoes();
        }
        
        public System.Threading.Tasks.Task<Clientes.Web.ClientesWcReference.SituacaoClienteModel[]> ListarSituacoesAsync() {
            return base.Channel.ListarSituacoesAsync();
        }
    }
}
